# Generated by Django 3.0.5 on 2020-08-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={'verbose_name': 'tutorial', 'verbose_name_plural': 'tutorials'},
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
